### ISSUE TITLE
Wrong RubyGems Homepage URL

### ISSUE THREAD

**Issue by junaruga** [ruby-concurrency/atomic#6]
On the RubyGem's page https://rubygems.org/gems/atomic
Homepage link is http://github.com/ruby-concurrency/ruby-atomic
Maybe, can you change to https://github.com/ruby-concurrency/atomic ?

Thanks

**Comment by pitr-ch** [comment]
@junaruga Thank you letting us know. We'll fix it.

**Comment by pitr-ch** [comment]
@jdantonio could you give me ownership? I'll fix the link, Thanks.

**Comment by jdantonio** [comment]
@pitr-ch I've added you as an owner to this and `ref`. I've also updated the links on the rubygems.org pags. Unfortunately the "homepage" link can't be changed through rubygems (as far as I know). It's is taken from the gemspec. Updating that link may require releasing an updated version of the gem.

**Comment by pitr-ch** [comment]
Fixed
