### ISSUE TITLE
1.1.100 Breaks JRuby and Bundler

### ISSUE THREAD

**Issue by jakelandis** [ruby-concurrency/atomic#7]
Reproduction case: 
Install JRuby and Bundler

With the following gems spec:
```
Gem::Specification.new do |s|
  s.name = "test"
  s.version = "0.0.0"
  s.date = "2018-03-05"
  s.summary = "test"
  s.authors = "test"
end
```

And the following Gemfile:
```
source 'https://rubygems.org'
gemspec

# Works
#gem 'atomic', "= 1.1.99"

# Broken
gem 'atomic', "= 1.1.100"
```

Run `bundler update`

`1.1.99` works fine, , `1.1.100` breaks with "Gem::Ext::BuildError: ERROR: Failed to build gem native extension."

This has pretty big impact on Logstash, since this gem was un-pinned until this issue.  New versions will get pinned to `1.1.99` , but for existing versions of Logstash, this issue breaks the plugin system without manually pinning.  Related issue: https://github.com/elastic/logstash/issues/9194

Is it possible to release a fix in `1.1.101`, or simply yank `1.1.100` ?

**Comment by jsvd** [comment]
I just seems that 1.1.100 wasn't released for the java platform. All other releases have two gems, -java and non -java.

**Comment by pitr-ch** [comment]
Sorry for the inconvenience, the version 1.1.100 was yanked. It had just a url fix in the spec. I'll release 101 later with both platforms.

**Comment by gfx** [comment]
atomic 1.1.100 was removed from rubygems.org, which breaks our code: Gemfile.lock is now invalid.

Do not remove a released gem, because it breaks the world. If you want to do so, release the previous version (e.g. 1.1.99) as the next version (1.1.101).

**Comment by pitr-ch** [comment]
I can do that. Wouldn't `bundle update atomic`fix the problem though?

**Comment by pitr-ch** [comment]
I've built a fixed version, see https://github.com/ruby-concurrency/atomic/releases/tag/1.1.101. It passes local tests and CI. It's not yet on rubygems though, since I've inherited this gem and it's my first time I've build its java extensions. Please download and let me know it works as expected. I'll upload to rubygems shortly after that.

**Comment by jakelandis** [comment]
Looks good.  I tested the repro case and it works now. 

Using `gem server` and
```
source 'http://localhost:8808'
gemspec
gem 'atomic', "= 1.1.101"
```
With JRuby
```
bundler update
Fetching source index from http://localhost:8808/
Resolving dependencies...
Using atomic 1.1.101 (java)
```

**Comment by pitr-ch** [comment]
Thanks, I'll upload shortly.

**Comment by pitr-ch** [comment]
Uploaded
